### ISSUE TITLE
Addon hangs on shutdown

### ISSUE THREAD

**Issue by 1358** [tamland/xbmc-addon-watchdog#3] opened 2013-03-17 11:57 UTC
It seems as if this addon prevents XBMC from shutting down in some cases, as there are threads that doesn't exit.
See https://github.com/OpenELEC/OpenELEC.tv/issues/2074 for more information.

http://forum.xbmc.org/showthread.php?tid=128896&pid=1368373#pid1368373

**Comment by gitbint** [comment] 2015-01-06 07:39
are you still working on this issue? i had that problem back on xbmc 11 or 12 and am still running into it with the new kodi release (14). I actually love what watchdog does, but kodi crashing each time i try to quit just doesn't justify its functions. are there any known workarounds (except not usign smb shares :)?

**Comment by tamland** [comment] 2015-01-06 16:10
But not 13? Haven't seen of heard about this issue since adding the 'please wait' dialog. Only known problems are when exiting before initialization has finished or the addon crash leaving a bad state, in which case there's really no other way to prevent that than *don't crash*.

**Comment by natrius** [comment] 2015-01-17 10:34
Using 13.2 atm i was not able to open OpenElec Configuration, read at openelecforum i should uninstall watchdog like said http://openelec.tv/forum/92-openelec-os-settings/67160-settings-not-available.

First wantet to try "deactivate" and the system freezed. Waited and after i did a hard reset and looked again in addon it was disabled. Uninstalled it after that and i was able to get in OpenElec Configuration again. Not tried to reproduce it -> should i?

**Comment by tamland** [comment] 2015-01-17 11:07
@natrius Read the rest of the thread. The deactivate button is known to be very buggy so best avoid it and restart instead.

I'm closing this now because it's turning into a 'me too' issue with nobody providing useful information. This is not a support forum. Please make a proper bug report and use the forum.kodi.tv thread.

**Closed by tamland** 2015-01-17 11:07 UTC
